<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hevlocation"
 *
 * Auto generated by Extension Builder 2015-02-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HEV Location',
	'description' => 'Location Search Form Elements and Postal Code / Settlement Name Selectors.',
	'category' => 'plugin',
	'author' => 'Joachim Rinck',
	'author_email' => 'jr@eoss.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);